import * as XLSX from 'xlsx'
import type { CatalogCategory } from '@/data/catalog'
export type BulkUnit={label:string;channel:'B2C'|'B2B'|'BOTH'|string;priceJod?:string;availability?:string;sortOrder?:number}
export type BulkProductRow={nameAr:string;sku:string;channel:'B2C'|'B2B'|'BOTH'|string;categorySlug?:string;shortDescriptionAr?:string;longDescriptionAr?:string;basePriceJod?:string;status?:string;publicVisible?:boolean;b2bAllowCustomUnit?:boolean;units?:BulkUnit[];imageUrl?:string;slug?:string}
const productHeaders={nameAr:['الاسم','اسم المنتج','name','name_ar'],sku:['SKU','sku'],channel:['القناة','channel'],categorySlug:['التصنيف','category_slug','category'],shortDescriptionAr:['الوصف المختصر','short_description_ar'],longDescriptionAr:['الوصف الكامل','long_description_ar'],basePriceJod:['السعر الأساسي JOD','base_price_jod'],status:['الحالة الداخلية','status'],publicVisible:['ظاهر للعملاء','public_visible'],b2bAllowCustomUnit:['وحدة مخصصة B2B','b2b_allow_custom_unit'],imageUrl:['رابط الصورة','image_url'],slug:['Slug','slug']} as const
const unitHeaders={sku:['SKU المنتج','product_sku','sku'],label:['اسم الوحدة','unit_label'],channel:['قناة الوحدة','unit_channel'],priceJod:['سعر الوحدة JOD','unit_price_jod'],availability:['توفر الوحدة','unit_availability'],sortOrder:['ترتيب','sort_order']} as const
function pick(row:Record<string,any>,names:readonly string[]){for(const name of names)if(row[name]!=null)return String(row[name]).trim();return''}
function bool(v:string){return['1','true','yes','y','نعم','صح'].includes(v.toLowerCase())}
export async function parseBulkProductFile(file:File):Promise<BulkProductRow[]>{const wb=XLSX.read(await file.arrayBuffer(),{type:'array'});const products=XLSX.utils.sheet_to_json<Record<string,any>>(wb.Sheets.Products??wb.Sheets[wb.SheetNames[0]],{defval:''});const units=wb.Sheets.Units?XLSX.utils.sheet_to_json<Record<string,any>>(wb.Sheets.Units,{defval:''}):[];const grouped=new Map<string,BulkUnit[]>();for(const row of units){const sku=pick(row,unitHeaders.sku).toUpperCase(),label=pick(row,unitHeaders.label);if(!sku||!label)continue;const list=grouped.get(sku)??[];list.push({label,channel:pick(row,unitHeaders.channel).toUpperCase(),priceJod:pick(row,unitHeaders.priceJod),availability:pick(row,unitHeaders.availability).toUpperCase(),sortOrder:Number(pick(row,unitHeaders.sortOrder)||list.length+1)});grouped.set(sku,list)}return products.map(row=>{const value:any={nameAr:pick(row,productHeaders.nameAr),sku:pick(row,productHeaders.sku).toUpperCase(),channel:pick(row,productHeaders.channel).toUpperCase()};for(const[key,names]of Object.entries(productHeaders)){if(key==='nameAr'||key==='sku'||key==='channel'||key==='publicVisible'||key==='b2bAllowCustomUnit')continue;const v=pick(row,names);if(v)value[key]=v}const visible=pick(row,productHeaders.publicVisible),custom=pick(row,productHeaders.b2bAllowCustomUnit);if(visible)value.publicVisible=bool(visible);if(custom)value.b2bAllowCustomUnit=bool(custom);const productUnits=grouped.get(value.sku);if(productUnits)value.units=productUnits;return value}).filter(row=>row.nameAr||row.sku)}
export function downloadBulkProductTemplate(categories:CatalogCategory[]){const products=XLSX.utils.json_to_sheet([{'الاسم':'مثال منتج','SKU':'CM-001','القناة':'BOTH','التصنيف':categories[0]?.slug??'','الوصف المختصر':'','الوصف الكامل':'','السعر الأساسي JOD':'','الحالة الداخلية':'DRAFT','ظاهر للعملاء':'نعم','وحدة مخصصة B2B':'لا','رابط الصورة':'','Slug':''}]);const units=XLSX.utils.json_to_sheet([{'SKU المنتج':'CM-001','اسم الوحدة':'علبة صغيرة','قناة الوحدة':'B2C','سعر الوحدة JOD':'5.000','توفر الوحدة':'AVAILABLE','ترتيب':1},{'SKU المنتج':'CM-001','اسم الوحدة':'صندوق شركات','قناة الوحدة':'B2B','سعر الوحدة JOD':'','توفر الوحدة':'AVAILABLE','ترتيب':1}]);const categoriesSheet=XLSX.utils.json_to_sheet(categories.map(x=>({'اسم التصنيف':x.label,'Slug المطلوب':x.slug})));const info=XLSX.utils.aoa_to_sheet([['تعليمات'],['ورقة Products: صف واحد لكل منتج. السعر الأساسي يستخدم فقط عندما لا توجد وحدات مسعّرة.'],['ورقة Units: SKU المنتج، اسم الوحدة، قناة الوحدة، سعرها، توفرها، وترتيبها.'],['وحدة B2C تحتاج سعرًا. وحدة B2B لا تظهر للأفراد.'],['SKU موجود = تحديث المنتج والوحدات المرفقة به فقط.']]);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,products,'Products');XLSX.utils.book_append_sheet(wb,units,'Units');XLSX.utils.book_append_sheet(wb,categoriesSheet,'Categories');XLSX.utils.book_append_sheet(wb,info,'Instructions');XLSX.writeFile(wb,'chef-mujahed-products-template.xlsx')}
