import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import ImageUploadField from '@/components/dashboard/ImageUploadField'
import { getDashboardBrandSettings, updateDashboardBrandSettings } from '@/data/dashboard'
import { useDashboard } from '@/state/DashboardContext'
import { useDashboardPreferences } from '@/state/DashboardPreferencesContext'
import { dashboardText } from '@/lib/dashboardI18n'
import { canManageUsers } from '@/lib/dashboardPermissions'
export default function SettingsPage(){const {role,runtime}=useDashboard();const {locale,setLocale}=useDashboardPreferences();const [logoUrl,setLogoUrl]=useState('');const [saving,setSaving]=useState(false);const [saved,setSaved]=useState(false);useEffect(()=>{void getDashboardBrandSettings(runtime).then(x=>setLogoUrl(x.logoUrl??'')).catch(()=>undefined)},[runtime]);const save=async()=>{try{setSaving(true);await updateDashboardBrandSettings(runtime,logoUrl);setSaved(true)}finally{setSaving(false)}};return <main className="space-y-6 p-4 lg:p-8" dir={locale==='en'?'ltr':'rtl'}><section className="rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)] p-6"><h1 className="text-xl font-bold">{dashboardText(locale,'title.settings')}</h1><p className="mt-2 text-sm text-[var(--color-text-muted)]">إعدادات لوحة التحكم الداخلية فقط.</p></section><section className="max-w-2xl rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)] p-6"><h2 className="font-bold">لغة لوحة التحكم</h2><div className="mt-4 flex gap-3" dir="ltr"><button type="button" onClick={()=>setLocale('ar')} className={locale==='ar'?'rounded-xl bg-[var(--color-text)] px-4 py-3 text-sm font-semibold text-white':'rounded-xl border border-[var(--color-border)] px-4 py-3 text-sm'}>العربية</button><button type="button" onClick={()=>setLocale('en')} className={locale==='en'?'rounded-xl bg-[var(--color-text)] px-4 py-3 text-sm font-semibold text-white':'rounded-xl border border-[var(--color-border)] px-4 py-3 text-sm'}>English</button></div></section><section className="max-w-2xl rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)] p-6"><h2 className="font-bold">لوجو لوحة التحكم</h2><p className="mt-1 text-sm text-[var(--color-text-muted)]">لوجو داخلي مستقل عن لوجو الموقع، مربع بنسبة 1:1.</p><div className="mt-4"><ImageUploadField label="لوجو الداشبورد" value={logoUrl} onChange={value=>{setLogoUrl(value);setSaved(false)}} storagePath="dashboard/brand-logo" help="PNG أو WebP بخلفية شفافة أفضل. سيظهر في الشريط الجانبي فقط." recommendedSize="512 × 512 px · 1:1" disabled={runtime.mode==='preview'} sharedNote="لا يغيّر لوجو الموقع العام."/><button type="button" disabled={saving} onClick={()=>void save()} className="mt-4 rounded-xl bg-[#2E1E17] px-5 py-3 text-sm font-bold !text-white disabled:opacity-50">{saving?'جاري الحفظ...':'حفظ لوجو الداشبورد'}</button>{saved?<span className="mr-3 text-sm font-semibold text-[#2E7D32]">تم الحفظ</span>:null}</div></section>{canManageUsers(role)?<Link to="/dashboard/users" className="block max-w-2xl rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)] p-6 font-semibold hover:bg-[var(--color-bg)]">إدارة المستخدمين</Link>:null}</main>}
