import { useEffect, useState } from 'react'
import { X } from '@phosphor-icons/react'
import Button from '@/components/ui/Button'
import { getPublicCategories, type CatalogCategory } from '@/data/catalog'
import { createDashboardProduct } from '@/data/dashboard'
import { emptyProductDraft, ProductFields, type ProductDraft } from '@/pages/dashboard/ProductCreatePage'
import type { DashboardRuntime } from '@/types/dashboard'

export default function ProductCreateDrawer({runtime,onClose,onCreated}:{runtime:DashboardRuntime;onClose:()=>void;onCreated:(id:string)=>void}){const [categories,setCategories]=useState<CatalogCategory[]>([]);const [draft,setDraft]=useState<ProductDraft>(emptyProductDraft);const [saving,setSaving]=useState(false);const [error,setError]=useState('');useEffect(()=>{void getPublicCategories().then(setCategories).catch(()=>setCategories([]))},[]);const save=async()=>{if(!draft.nameAr.trim()||!draft.sku.trim()){setError('اسم المنتج وSKU مطلوبان.');return}try{setSaving(true);setError('');const result=await createDashboardProduct(runtime,draft);onCreated(result.product.id)}catch(err:any){setError(String(err?.message??'تعذر إنشاء المنتج'))}finally{setSaving(false)}};return <div className="fixed inset-0 z-50 bg-black/35" role="dialog" aria-modal="true" aria-label="إضافة منتج جديد" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><section className="absolute inset-x-0 bottom-0 max-h-[92vh] overflow-y-auto rounded-t-3xl bg-[var(--color-surface)] p-5 shadow-2xl md:inset-y-0 md:right-0 md:left-auto md:w-[620px] md:rounded-none md:p-7" dir="rtl"><div className="flex items-center justify-between border-b border-[var(--color-border)] pb-4"><button type="button" onClick={onClose} className="grid size-10 place-items-center rounded-lg hover:bg-[var(--color-bg)]" aria-label="إغلاق"><X size={20}/></button><div className="text-right"><h2 className="text-xl font-bold">إضافة منتج جديد</h2><p className="mt-1 text-xs text-[var(--color-text-muted)]">بعد الإنشاء تفتح صفحة المنتج لاستكمال الوحدات والتخصيص.</p></div></div>{error?<div className="mt-4 rounded-xl bg-[#FDECEC] p-3 text-sm text-[#C62828]">{error}</div>:null}<div className="mt-5"><ProductFields draft={draft} setDraft={setDraft} categories={categories}/></div><div className="sticky bottom-0 mt-6 flex justify-start gap-3 border-t border-[var(--color-border)] bg-[var(--color-surface)] pt-4"><Button disabled={saving} onClick={()=>void save()}>{saving?'جاري الإنشاء...':'إنشاء ومتابعة التعديل'}</Button><Button variant="ghost" onClick={onClose}>إلغاء</Button></div></section></div>}
