import { useState } from 'react'
import { NavLink, useLocation } from 'react-router-dom'
import { Bell, CaretLeft, ChartBar, ClipboardText, Factory, Globe, House, List, Package, UsersThree, X } from '@phosphor-icons/react'
import DashboardBrand from './DashboardBrand'
import { canManageContent, canManageProductionAccess } from '@/lib/dashboardPermissions'
import { useDashboard } from '@/state/DashboardContext'
import { useDashboardPreferences } from '@/state/DashboardPreferencesContext'
import { dashboardText, roleText } from '@/lib/dashboardI18n'
import NotificationBell from '@/components/dashboard/NotificationBell'
const items=[{to:'/dashboard',key:'home',icon:House,end:true},{to:'/dashboard/requests',key:'requests',icon:ClipboardText},{to:'/dashboard/customers',key:'customers',icon:UsersThree},{to:'/dashboard/products',key:'products',icon:Package},{to:'/dashboard/content',key:'content',icon:Globe,visible:canManageContent},{to:'/dashboard/production-access',key:'kitchen',icon:Factory,visible:canManageProductionAccess},{to:'/dashboard/notifications',key:'notifications',icon:Bell},{to:'/dashboard/reports',key:'reports',icon:ChartBar}] as const
function title(path:string,locale:'ar'|'en'){if(path.includes('/notifications'))return dashboardText(locale,'title.notifications');if(path.includes('/reports'))return dashboardText(locale,'title.reports');if(path.includes('/content'))return dashboardText(locale,'title.content');if(path.includes('/products'))return dashboardText(locale,'title.products');if(path.includes('/customers'))return dashboardText(locale,'title.customers');if(path.includes('/requests'))return dashboardText(locale,'title.requests');if(path.includes('/settings'))return dashboardText(locale,'title.settings');return dashboardText(locale,'title.dashboard')}
function navItems(role:any){return items.filter(item=>!item.visible||item.visible(role))}
export function DashboardSidebar(){const {role,runtime,logout}=useDashboard();const {locale}=useDashboardPreferences();return <aside className="fixed inset-y-0 right-0 z-30 hidden w-[260px] flex-col border-l border-[var(--color-border)] bg-[var(--color-surface)] px-4 py-6 lg:flex"><div className="flex items-center gap-3 border-b border-[var(--color-border)] pb-5"><DashboardBrand/><div><p className="font-bold">{dashboardText(locale,'brand.dashboard')}</p><p className="text-[11px] text-[var(--color-accent)]">{dashboardText(locale,'brand.name')}</p></div></div><nav className="mt-5 space-y-1.5">{navItems(role).map(item=>{const Icon=item.icon;return <NavLink key={item.to} to={item.to} end={item.end} className={({isActive})=>'flex min-h-11 items-center gap-3 rounded-lg px-4 text-sm '+(isActive?'bg-[var(--color-bg)] font-semibold text-[var(--color-text-muted)]':'text-[#57534E] hover:bg-[var(--color-bg)]')}><Icon size={19}/>{dashboardText(locale,'nav.'+item.key)}</NavLink>})}</nav><NavLink to="/dashboard/settings" className="mt-auto flex items-center gap-3 border-t border-[var(--color-border)] pt-4 text-right"><div className="grid size-9 place-items-center rounded-full bg-[var(--color-border)] text-sm font-semibold">م</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{runtime.access?.displayName??'مدير النظام'}</p><p className="text-xs text-[var(--color-text-muted)]">{roleText(locale,role)}</p></div><CaretLeft size={16}/></NavLink><button type="button" onClick={()=>void logout()} className="mt-3 min-h-11 w-full rounded-lg border border-[var(--color-border)] px-3 py-2 text-sm text-[var(--color-text-muted)]">{dashboardText(locale,'common.logout')}</button></aside>}
export function DashboardTopbar(){const location=useLocation();const {role,runtime,logout}=useDashboard();const {locale}=useDashboardPreferences();const [menuOpen,setMenuOpen]=useState(false);const closeMenu=()=>setMenuOpen(false);return <><header className="sticky top-0 z-20 flex h-[68px] items-center justify-between border-b border-[var(--color-border)] bg-[var(--color-surface)] px-4 lg:px-8"><h1 className="text-lg font-bold lg:text-[22px]">{title(location.pathname,locale)}</h1><div className="flex items-center gap-2"><NotificationBell/><button type="button" onClick={()=>setMenuOpen(true)} aria-label="فتح القائمة" className="grid size-10 place-items-center rounded-lg border border-[var(--color-border)] lg:hidden"><List size={21}/></button></div></header>{menuOpen?<><button type="button" aria-label="إغلاق القائمة" onClick={closeMenu} className="fixed inset-0 z-30 bg-black/25 lg:hidden"/><aside role="dialog" aria-modal="true" aria-label="قائمة لوحة التحكم" className="fixed inset-y-0 right-0 z-40 flex w-[min(86vw,340px)] flex-col bg-[var(--color-surface)] p-4 shadow-[-12px_0_30px_rgba(29,23,20,.15)] lg:hidden"><div className="flex items-center justify-between border-b border-[var(--color-border)] pb-4"><button type="button" onClick={closeMenu} aria-label="إغلاق القائمة" className="grid size-10 place-items-center rounded-lg hover:bg-[var(--color-bg)]"><X size={20}/></button><div className="flex items-center gap-3 text-right"><div><p className="text-sm font-bold">{runtime.access?.displayName??'مدير النظام'}</p><p className="text-xs text-[var(--color-text-muted)]">{roleText(locale,role)}</p></div><DashboardBrand/></div></div><nav className="mt-4 space-y-1 overflow-y-auto">{navItems(role).map(item=>{const Icon=item.icon;return <NavLink key={item.to} to={item.to} end={item.end} onClick={closeMenu} className={({isActive})=>'flex min-h-12 items-center gap-3 rounded-xl px-4 text-sm '+(isActive?'bg-[var(--color-bg)] font-semibold text-[var(--color-text)]':'text-[var(--color-text-muted)]')}><Icon size={20}/>{dashboardText(locale,'nav.'+item.key)}</NavLink>})}</nav><NavLink to="/dashboard/settings" onClick={closeMenu} className="mt-auto flex min-h-12 items-center rounded-xl border-t border-[var(--color-border)] pt-4 text-sm font-semibold">{dashboardText(locale,'title.settings')}</NavLink><button type="button" onClick={()=>void logout()} className="mt-3 min-h-11 rounded-xl border border-[var(--color-border)] px-4 text-sm font-semibold text-[var(--color-text-muted)]">{dashboardText(locale,'common.logout')}</button></aside></>:null}</>}
