import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { Link } from 'react-router-dom'
import { Bell } from '@phosphor-icons/react'
import { listDashboardRequests } from '@/data/dashboard'
import { supabase } from '@/lib/supabase'
import { useDashboard } from '@/state/DashboardContext'
import type { DashboardRequestListItem } from '@/types/dashboard'
function isAttention(item:DashboardRequestListItem){return item.status==='NEW'||item.status==='AWAITING_CONFIRMATION'||(item.status==='READY'&&item.fulfillment_type==='DELIVERY')}
export default function NotificationBell(){const {runtime}=useDashboard();const [items,setItems]=useState<DashboardRequestListItem[]>([]);const [open,setOpen]=useState(false);const root=useRef<HTMLDivElement>(null);const load=useCallback(async()=>{try{const result=await listDashboardRequests(runtime,{pageSize:20});setItems(result.items.filter(isAttention))}catch{}},[runtime]);useEffect(()=>{void load();const channel=supabase.channel('dashboard-request-notifications').on('postgres_changes',{event:'*',schema:'public',table:'requests'},()=>void load()).subscribe();return()=>{void supabase.removeChannel(channel)}},[load]);useEffect(()=>{const outside=(event:PointerEvent)=>{if(root.current&&!root.current.contains(event.target as Node))setOpen(false)};const escape=(event:KeyboardEvent)=>{if(event.key==='Escape')setOpen(false)};document.addEventListener('pointerdown',outside);document.addEventListener('keydown',escape);return()=>{document.removeEventListener('pointerdown',outside);document.removeEventListener('keydown',escape)}},[]);const latest=useMemo(()=>items.slice(0,5),[items]);return <div ref={root} className="relative"><button type="button" onClick={()=>setOpen(value=>!value)} className="relative grid size-10 place-items-center rounded-xl border border-[var(--color-border)] bg-[var(--color-surface)] text-[var(--color-text-muted)] hover:bg-[var(--color-bg)]" aria-label="التنبيهات"><Bell size={21} weight="regular"/>{items.length>0?<span className="absolute -left-1 -top-1 grid min-w-5 place-items-center rounded-full bg-[#B42318] px-1 text-[10px] font-bold leading-5 text-white">{items.length>9?'9+':items.length}</span>:null}</button>{open?<div className="absolute left-0 top-12 z-50 w-[340px] overflow-hidden rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)] shadow-xl" dir="rtl"><div className="flex items-center justify-between border-b border-[var(--color-border)] px-4 py-3"><Link to="/dashboard/notifications" onClick={()=>setOpen(false)} className="text-xs font-semibold text-[var(--color-text-muted)]">عرض الكل</Link><strong>التنبيهات</strong></div>{latest.length?latest.map(item=><Link key={item.id} to={'/dashboard/requests/'+item.id} onClick={()=>setOpen(false)} className="block border-b border-[var(--color-border)] px-4 py-3 text-right hover:bg-[var(--color-bg)]"><strong className="block text-sm">{item.status==='NEW'?'طلب جديد يحتاج مراجعة':item.status==='AWAITING_CONFIRMATION'?'طلب بانتظار التأكيد':'طلب جاهز للتوصيل'}</strong><span className="mt-1 block text-xs text-[var(--color-text-muted)]">{item.reference} · {item.customer_label}</span></Link>):<p className="p-5 text-center text-sm text-[var(--color-text-muted)]">لا توجد تنبيهات جديدة</p>}</div>:null}</div>}
