import { useEffect, useRef, type ReactNode } from 'react'
import { useDashboardPreferences } from '@/state/DashboardPreferencesContext'

const copy: Record<string,string> = {
  'إدارة المنتجات':'Product management','إدارة الطلبات':'Request management','قائمة الطلبات':'Requests','إدارة العملاء':'Customer management','العملاء والشركات':'Customers & companies','إدارة محتوى الموقع':'Website content','المستخدمون والصلاحيات':'Users & permissions','التنبيهات التشغيلية':'Operational notifications','التقارير والتحليلات':'Reports & analytics','إعدادات لوحة التحكم':'Dashboard settings',
  'إضافة':'Add','إضافة منتج':'Add product','إضافة منتج جديد':'Add new product','إضافة طلب داخلي':'Add internal request','إضافة مستخدم':'Add user','إغلاق':'Close','إلغاء':'Cancel','حفظ':'Save','حفظ التغييرات':'Save changes','تسجيل الخروج':'Log out','تعديل':'Edit','تحديث':'Update','تفاصيل':'Details','فتح':'Open','عرض الكل':'View all','مسح الفلاتر':'Clear filters','إعادة المحاولة':'Try again','بحث باسم المنتج أو SKU':'Search by product name or SKU','بحث بالمرجع، العميل أو الهاتف':'Search by reference, customer, or phone',
  'الأساسيات':'Basics','الوحدات والصيغ':'Units & formats','التخصيص':'Customisation','القنوات والظهور':'Channels & visibility','يباع في':'Sold through','الحالة الداخلية':'Internal status','ظاهر للعملاء':'Visible to customers','السماح بطلب وحدة مخصصة للشركات':'Allow a custom unit for companies','التوفر':'Availability','متاح':'Available','غير متاح':'Unavailable','كمية محدودة':'Limited quantity','موسمي':'Seasonal','نشط':'Active','غير نشط':'Inactive','مسودة':'Draft','مؤرشف':'Archived','جاهز للنشر':'Ready to publish','عام':'Public','مخفي':'Hidden',
  'المنتج':'Product','المنتجات':'Products','التصنيف':'Category','القناة':'Channel','السعر الأساسي':'Base price','السعر الأساسي JOD':'Base price (JOD)','السعر JOD':'Price (JOD)','السعر النهائي':'Final price','SKU هو الرمز الداخلي الفريد للمنتج؛ يساعد الفريق في البحث والتطابق والاستيراد.':'SKU is the product’s unique internal code. It helps the team search, match, and import products.','بدون تصنيف':'Uncategorised','بدون SKU':'No SKU','سعر الوحدة هو السعر المعتمد للعميل ويطغى على السعر الأساسي.':'The unit price is the customer price and overrides the base price.','حذف الوحدة':'Delete unit','إزالة':'Remove',
  'كل القنوات':'All channels','كل الحالات':'All statuses','كل التوفر':'All availability','كل المصادر':'All sources','كل الطلبات':'All requests','اليوم':'Today','أمس':'Yesterday','الأسبوع الماضي':'Last week','الشهر الماضي':'Last month','آخر 7 أيام':'Last 7 days','آخر 30 يوم':'Last 30 days','الفلاتر غير مفعلة':'No active filters','لا توجد منتجات':'No products','لا توجد طلبات':'No requests','لا توجد بيانات لهذه الفترة.':'No data for this period.','لا توجد بيانات دفع لهذه الفترة.':'No payment data for this period.',
  'العميل':'Customer','العميل / الشركة':'Customer / company','اسم العميل':'Customer name','اسم الشركة':'Company name','اسم جهة الاتصال':'Contact name','رقم الهاتف':'Phone number','البريد الإلكتروني':'Email address','البريد الإلكتروني (اختياري)':'Email address (optional)','جهة التواصل':'Contact','العنوان':'Address','شركة B2B':'B2B company','عميل B2C':'B2C customer','الأفراد B2C':'Retail (B2C)','الشركات B2B':'Business (B2B)','الأفراد والشركات':'Retail & business',
  'الدفع':'Payment','حالة الدفع':'Payment status','طريقة الدفع':'Payment method','الدفع عند الاستلام':'Cash on delivery','استلام':'Collection','توصيل':'Delivery','التوصيل والاستلام':'Delivery & collection','تاريخ الطلب':'Request date','التاريخ المفضل':'Preferred date','المرجع':'Reference','المسؤول':'Assignee','المصدر':'Source','النوع':'Type','النوع والمصدر':'Type & source','الإجراءات':'Actions','الإجراء':'Action','الحالة':'Status','فاتورة مبيعات':'Sales invoice',
  'ملاحظات داخلية':'Internal notes','أضف ملاحظة داخلية':'Add an internal note','ملاحظات عامة من العميل':'Customer notes','سجل النشاط':'Activity log','آخر النشاطات':'Latest activity','آخر الطلبات الواردة':'Latest requests','آخر طلب':'Latest request','أهلاً بك مجدداً':'Welcome back','ملخص النشاط التشغيلي لهذا اليوم':'Today’s operational activity summary','إجمالي':'Total','إجمالي الطلبات':'Total requests',
  'لغة لوحة التحكم وCMS':'Dashboard and CMS language','إدارة المستخدمين':'Manage users','إعدادات التشغيل والوصول الداخلي.':'Operational and internal-access settings.','إعادة ضبط البيانات':'Reset data','إعادة ضبط كاملة':'Full reset','استعادة النسخة':'Restore snapshot','التطبيق التشغيلي':'Operational app','الوصول الداخلي مطلوب':'Internal access required','لا تملك صلاحية لتنفيذ هذا الإجراء':'You do not have permission to perform this action','حدث خطأ في تحميل البيانات':'Could not load data','واجهنا مشكلة في جلب معلومات لوحة التحكم. يرجى المحاولة مجدداً.':'There was a problem loading dashboard data. Please try again.',
  'التنبيهات':'Notifications','التقارير':'Reports','المستخدمون':'Users','المحتوى':'Content','وصول المطبخ':'Kitchen access','الرئيسية':'Home','لوحة التحكم':'Dashboard','الشيف مجاهد':'Chef Mujahed','العربية':'Arabic',
  'جديد':'New','يحتاج مراجعة':'Needs review','بانتظار التأكيد':'Awaiting confirmation','تمت الموافقة':'Approved','قيد التحضير':'Preparing','جاهز':'Ready','قيد التوصيل':'Out for delivery','مكتمل':'Completed','ملغي':'Cancelled','غير مسجل':'Unrecorded','بانتظار الدفع':'Awaiting payment','مدفوع':'Paid','مدفوع جزئياً':'Partially paid',
  'استيراد Bulk':'Bulk import','استيراد منتجات Bulk':'Bulk product import','اختيار ملف CSV / XLSX':'Choose CSV / XLSX file','تم الاستيراد بنجاح':'Import completed','الصف':'Row','الأخطاء':'Errors','الصلاحية':'Permission','المستخدم':'User','آخر دخول':'Last sign-in','كلمة مرور جديدة':'New password','إنشاء':'Create','إنشاء ومتابعة التعديل':'Create and continue editing','الظهور':'Visibility','الصورة الرئيسية':'Main image','الصورة الرئيسية للمنتج':'Product main image','صور المنتجات':'Product images','الأسئلة الشائعة':'FAQs','الشروط والأحكام':'Terms & conditions'
}
function translate(value:string){const trimmed=value.trim();return copy[trimmed]?value.replace(trimmed,copy[trimmed]):value}
export default function DashboardLocaleBridge({children}:{children:ReactNode}){const{locale}=useDashboardPreferences();const root=useRef<HTMLDivElement>(null);const originals=useRef(new WeakMap<Text,string>());const attributes=useRef(new WeakMap<Element,Map<string,string>>());useEffect(()=>{const localize=(node:Node)=>{if(node.nodeType===Node.TEXT_NODE){const text=node as Text;const original=originals.current.get(text)??text.nodeValue??'';if(!originals.current.has(text))originals.current.set(text,original);text.nodeValue=locale==='en'?translate(original):original;return}if(node.nodeType!==Node.ELEMENT_NODE)return;const element=node as Element;const saved=attributes.current.get(element)??new Map<string,string>();['placeholder','aria-label','title','dir'].forEach(name=>{const current=element.getAttribute(name);if(current==null)return;const original=saved.get(name)??current;saved.set(name,original);const localized=name==='dir'&&original==='rtl'&&locale==='en'?'ltr':locale==='en'?translate(original):original;element.setAttribute(name,localized)});attributes.current.set(element,saved);element.childNodes.forEach(localize)};if(!root.current)return;localize(root.current);const observer=new MutationObserver(records=>records.forEach(record=>record.addedNodes.forEach(localize)));observer.observe(root.current,{childList:true,subtree:true});return()=>observer.disconnect()},[locale]);return <div ref={root} className="contents">{children}</div>}
