import { useCallback, useEffect, useState } from 'react'
import { Link, useParams, useSearchParams } from 'react-router-dom'
import {
  getDashboardProduct,
  saveDashboardProductCustomization,
  saveDashboardProductUnits,
  updateDashboardProductBasic,
} from '@/data/dashboard'
import { useDashboard } from '@/state/DashboardContext'
import type { DashboardProductDetail } from '@/types/dashboard'
import { DashboardError, DashboardLoading, DashboardRestricted } from '@/components/dashboard/DashboardStates'
import { canEditBasePrice } from '@/lib/dashboardPermissions'
import Button from '@/components/ui/Button'
import ImageUploadField from '@/components/dashboard/ImageUploadField'
import { Trash } from '@phosphor-icons/react'

type Tab = 'basic' | 'units' | 'customization'

export default function ProductEditPage() {
  const { id = '' } = useParams(); const [searchParams,setSearchParams]=useSearchParams(); const tab=(searchParams.get('tab') as Tab)||'basic'; const {runtime,role}=useDashboard()
  const [data,setData]=useState<DashboardProductDetail|null>(null); const [draft,setDraft]=useState<Record<string,any>>({}); const [error,setError]=useState(false); const [restricted,setRestricted]=useState(false); const [saving,setSaving]=useState(false); const [saved,setSaved]=useState(false)
  const load=useCallback(async()=>{try{setError(false);const result=await getDashboardProduct(runtime,id);setData(result);setDraft({...result.product,primary_image_url:result.images?.find((image:any)=>image.is_primary)?.image_url??''})}catch{setError(true)}},[runtime,id])
  useEffect(()=>{void load()},[load])
  if(error)return <DashboardError onRetry={()=>void load()}/>
  if(!data)return <DashboardLoading/>
  if(restricted)return <DashboardRestricted/>
  const mutate=async(operation:()=>Promise<DashboardProductDetail>)=>{try{setSaving(true);setSaved(false);const result=await operation();setData(result);setDraft({...result.product,primary_image_url:result.images?.find((image:any)=>image.is_primary)?.image_url??''});setSaved(true)}catch(err:any){if(String(err?.message??err).toLowerCase().includes('permission')||String(err?.message??err).toLowerCase().includes('supervisor'))setRestricted(true);else setError(true)}finally{setSaving(false)}}
  const saveBasic=()=>mutate(()=>updateDashboardProductBasic(runtime,id,{nameAr:draft.name_ar,shortDescriptionAr:draft.short_description_ar,longDescriptionAr:draft.long_description_ar,categoryId:draft.category_id,basePriceJod:draft.base_price_jod,availability:draft.availability,status:draft.status,channel:draft.channel,publicVisible:draft.public_visible,b2bAllowCustomUnit:draft.b2b_allow_custom_unit,internalNotes:draft.internal_notes,primaryImageUrl:draft.primary_image_url}))
  return <main className="space-y-6 p-4 lg:p-8">
    <div className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><div className="text-sm text-[var(--color-text-muted)]"><Link to="/dashboard/products">المنتجات</Link> ‹ <strong>{data.product.name_ar}</strong></div><h2 className="mt-2 text-2xl font-bold">{data.product.name_ar}</h2><p className="mt-1 text-xs text-[var(--color-text-muted)]">SKU: {data.product.sku||'--'} · {data.product.channel} · {data.product.status}</p></div>{saved?<span className="self-start rounded-full bg-[#E8F5E9] px-3 py-1 text-xs font-semibold text-[#2E7D32]">تم الحفظ</span>:null}</div>
    <div className="flex overflow-x-auto border-b border-[var(--color-border)]">{[['basic','الأساسيات'],['units','الوحدات والصيغ'],['customization','التخصيص']].map(([value,label])=><button key={value} onClick={()=>setSearchParams({tab:value})} className={`shrink-0 border-b-2 px-4 py-3 text-sm ${tab===value?'border-[var(--color-text-muted)] font-semibold':'border-transparent text-[#78716C]'}`}>{label}</button>)}</div>

    {tab==='basic'?<section className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_340px]" dir="ltr"><div dir="rtl" className="space-y-5 rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)] p-5 lg:p-7"><Section title="المعلومات الأساسية" description="ابدأ بالمعلومات التي يراها العميل، ثم افتح التفاصيل المتقدمة فقط عند الحاجة."><Field label="اسم المنتج" value={draft.name_ar??''} onChange={v=>setDraft({...draft,name_ar:v})}/><TextField label="الوصف المختصر" value={draft.short_description_ar??''} onChange={v=>setDraft({...draft,short_description_ar:v})}/><TextField label="الوصف الكامل" value={draft.long_description_ar??''} onChange={v=>setDraft({...draft,long_description_ar:v})}/><div className="grid gap-4 sm:grid-cols-2"><label><span className="mb-2 block text-sm font-semibold">التصنيف</span><select value={draft.category_id??''} onChange={e=>setDraft({...draft,category_id:e.target.value})} className="h-11 w-full rounded-xl border border-[var(--color-border)] bg-white px-3"><option value="">بدون تصنيف</option>{data.categories.map(c=><option key={c.id} value={c.id}>{c.name_ar}</option>)}</select></label><label><span className="mb-2 block text-sm font-semibold">السعر الأساسي JOD</span><input type="number" step="0.001" disabled={!canEditBasePrice(role)} value={draft.base_price_jod??''} onChange={e=>setDraft({...draft,base_price_jod:e.target.value})} className="h-11 w-full rounded-xl border border-[var(--color-border)] bg-white px-3 disabled:bg-[var(--color-bg)]"/></label></div></Section>
      <Section title="القنوات والظهور" description="اختر أين يباع المنتج. التوفر يدار من كل وحدة أو صيغة، وليس من هنا."><div className="grid gap-4 sm:grid-cols-2"><Select label="يباع في" value={draft.channel??'BOTH'} onChange={v=>setDraft({...draft,channel:v})} options={[['B2C','الأفراد B2C'],['B2B','الشركات B2B'],['BOTH','الأفراد والشركات']]}/><Select label="الحالة الداخلية" value={draft.status??'DRAFT'} onChange={v=>setDraft({...draft,status:v})} options={[['DRAFT','مسودة'],['ACTIVE','جاهز للنشر'],['ARCHIVED','مؤرشف']]}/></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><Toggle checked={Boolean(draft.public_visible)} onChange={v=>setDraft({...draft,public_visible:v})} label="ظاهر للعملاء" description="يظهر فقط في القنوات التي اخترتها."/><Toggle checked={Boolean(draft.b2b_allow_custom_unit)} onChange={v=>setDraft({...draft,b2b_allow_custom_unit:v})} label="السماح بطلب وحدة مخصصة للشركات" description="يظهر للشركات فقط عندما يكون المنتج متاحًا لها."/></div></Section>
      <Section title="الصورة الرئيسية" description="ارفع الصورة من جهازك أو اسحبها وأفلتها. الرابط المباشر يبقى خياراً إضافياً."><ImageUploadField label="الصورة الرئيسية للمنتج" value={draft.primary_image_url??''} onChange={v=>setDraft({...draft,primary_image_url:v})} storagePath={`products/${id}/primary`} help="استخدم صورة منتج واضحة بخلفية نظيفة وقص مربع قدر الإمكان. ستظهر في بطاقات المنتجات وصفحة التفاصيل." recommendedSize="1200 × 1200 px · 1:1" disabled={runtime.mode==='preview'} sharedNote="هذه الصورة هي الصورة الرئيسية للمنتج وتُستخدم في بطاقات المنتج وصفحة التفاصيل."/></Section>
      <div className="sticky bottom-4 flex justify-end gap-3 rounded-xl border border-[var(--color-border)] bg-[var(--color-surface)]/95 p-3 shadow-lg backdrop-blur"><Button variant="ghost" onClick={()=>void load()}>تراجع</Button><Button disabled={saving} onClick={()=>void saveBasic()}>{saving?'جاري الحفظ...':'حفظ التغييرات'}</Button></div></div>
      <aside dir="rtl" className="h-fit space-y-4 rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)] p-5"><h3 className="font-bold">ملخص المنتج</h3><Summary label="SKU" value={data.product.sku||'--'}/><Summary label="القناة" value={draft.channel}/><Summary label="الحالة" value={draft.status}/><Summary label="التوفر" value={draft.availability}/><label><span className="mb-2 block text-sm font-semibold">ملاحظات داخلية</span><textarea rows={6} value={draft.internal_notes??''} onChange={e=>setDraft({...draft,internal_notes:e.target.value})} className="w-full rounded-xl border border-[var(--color-border)] bg-white p-3 text-sm outline-none"/></label></aside></section>:null}
    {tab==='units'?<UnitsEditor data={data} saving={saving} onSave={units=>void mutate(()=>saveDashboardProductUnits(runtime,id,units))}/>:null}
    {tab==='customization'?<CustomizationEditor data={data} saving={saving} onSave={fields=>void mutate(()=>saveDashboardProductCustomization(runtime,id,fields))}/>:null}
  </main>
}

function Section({title,description,children}:{title:string;description:string;children:any}){return <section className="rounded-xl border border-[var(--color-border)] p-5"><h3 className="font-bold">{title}</h3><p className="mt-1 text-xs leading-5 text-[var(--color-text-muted)]">{description}</p><div className="mt-5 space-y-4">{children}</div></section>}
function Field({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="block"><span className="mb-2 block text-sm font-semibold">{label}</span><input value={value} onChange={e=>onChange(e.target.value)} className="h-11 w-full rounded-xl border border-[var(--color-border)] bg-white px-3 outline-none"/></label>}
function TextField({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="block"><span className="mb-2 block text-sm font-semibold">{label}</span><textarea rows={4} value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-xl border border-[var(--color-border)] bg-white p-3 outline-none"/></label>}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:Array<[string,string]>}){return <label><span className="mb-2 block text-sm font-semibold">{label}</span><select value={value} onChange={e=>onChange(e.target.value)} className="h-11 w-full rounded-xl border border-[var(--color-border)] bg-white px-3">{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}
function Toggle({checked,onChange,label,description}:{checked:boolean;onChange:(v:boolean)=>void;label:string;description:string}){return <label className="rounded-xl bg-[var(--color-bg)] p-4"><span className="flex items-center gap-2"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/><strong className="text-sm">{label}</strong></span><span className="mt-1 block text-xs leading-5 text-[var(--color-text-muted)]">{description}</span></label>}
function Summary({label,value}:{label:string;value:any}){return <div className="flex items-center justify-between border-b border-[var(--color-border)] pb-3 text-sm"><span className="font-semibold">{value||'--'}</span><span className="text-[var(--color-text-muted)]">{label}</span></div>}

function UnitsEditor({data,saving,onSave}:{data:DashboardProductDetail;saving:boolean;onSave:(units:Array<Record<string,unknown>>)=>void}){const[units,setUnits]=useState(data.units.map(u=>({...u})));useEffect(()=>setUnits(data.units.map(u=>({...u}))),[data.units]);const channel=data.product.channel??'BOTH';const choices=channel==='B2C'?[['B2C','B2C']]:channel==='B2B'?[['B2B','B2B']]:[['B2C','B2C'],['B2B','B2B'],['BOTH','كلاهما']];const add=()=>setUnits([...units,{id:'',label_ar:'',channel:channel==='BOTH'?'B2C':channel,price_jod:'',availability:'AVAILABLE',sort_order:units.length+1}]);return <section className="rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)] p-5 lg:p-8"><div className="flex items-end justify-between"><Button variant="secondary" onClick={add}>+ إضافة وحدة</Button><div className="text-right"><h2 className="text-lg font-bold">الوحدات والصيغ</h2><p className="mt-1 text-sm text-[var(--color-text-muted)]">سعر الوحدة هو السعر المعتمد للعميل ويطغى على السعر الأساسي.</p></div></div><div className="mt-6 space-y-3">{units.map((unit,index)=><div key={unit.id||index} className="grid gap-3 rounded-xl border border-[var(--color-border)] p-4 md:grid-cols-[2fr_1fr_1fr_1fr_auto]"><input placeholder="مثال: قطعة / علبة / كيلو" value={unit.label_ar??''} onChange={e=>setUnits(units.map((u,i)=>i===index?{...u,label_ar:e.target.value}:u))} className="h-10 rounded-lg border border-[var(--color-border)] px-3"/><input type="number" step="0.001" placeholder="السعر JOD" value={unit.price_jod??''} onChange={e=>setUnits(units.map((u,i)=>i===index?{...u,price_jod:e.target.value}:u))} className="h-10 rounded-lg border border-[var(--color-border)] px-3"/><select value={unit.channel??'B2C'} onChange={e=>setUnits(units.map((u,i)=>i===index?{...u,channel:e.target.value}:u))} className="h-10 rounded-lg border border-[var(--color-border)] px-3">{choices.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select value={unit.availability??'AVAILABLE'} onChange={e=>setUnits(units.map((u,i)=>i===index?{...u,availability:e.target.value}:u))} className="h-10 rounded-lg border border-[var(--color-border)] px-3"><option value="AVAILABLE">متاح</option><option value="LIMITED">كمية محدودة</option><option value="UNAVAILABLE">غير متاح</option></select><button type="button" aria-label="حذف الوحدة" title="حذف الوحدة" onClick={()=>setUnits(units.filter((_,i)=>i!==index))} className="grid size-10 place-items-center rounded-lg text-[#C62828] hover:bg-[#FDECEC]"><Trash size={18}/></button></div>)}</div><div className="mt-6 flex justify-end border-t border-[var(--color-border)] pt-5"><Button disabled={saving} onClick={()=>onSave(units.filter(u=>String(u.label_ar??'').trim()).map((u,i)=>({id:u.id||'',labelAr:u.label_ar,channel:u.channel,priceJod:u.price_jod,availability:u.availability,descriptionAr:u.description_ar??'',sortOrder:i+1})))}>حفظ الوحدات</Button></div></section>}
function CustomizationEditor({data,saving,onSave}:{data:DashboardProductDetail;saving:boolean;onSave:(fields:Array<Record<string,unknown>>)=>void}){const[fields,setFields]=useState(data.customization.map(f=>({...f,options:(f.options??[]).map((o:any)=>({...o}))})));useEffect(()=>setFields(data.customization.map(f=>({...f,options:(f.options??[]).map((o:any)=>({...o}))}))),[data.customization]);const add=()=>setFields([...fields,{id:'',label_ar:'',field_type:'text',is_required:false,is_active:true,sort_order:fields.length+1,options:[]}]);return <section className="rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)] p-5 lg:p-8"><div className="flex items-end justify-between"><Button variant="secondary" onClick={add}>+ إضافة حقل</Button><div className="text-right"><h2 className="text-lg font-bold">التخصيص</h2><p className="mt-1 text-sm text-[var(--color-text-muted)]">أضف حقولاً فقط عندما المنتج يحتاج تخصيصاً فعلياً.</p></div></div><div className="mt-6 space-y-4">{fields.map((field,index)=><div key={field.id||index} className="rounded-xl border border-[var(--color-border)] p-4"><div className="grid gap-3 md:grid-cols-[2fr_1fr_auto_auto_auto]"><input placeholder="اسم الحقل" value={field.label_ar??''} onChange={e=>setFields(fields.map((f,i)=>i===index?{...f,label_ar:e.target.value}:f))} className="h-10 rounded-lg border border-[var(--color-border)] px-3"/><select value={field.field_type??'text'} onChange={e=>setFields(fields.map((f,i)=>i===index?{...f,field_type:e.target.value,options:e.target.value==='text'?[]:f.options}:f))} className="h-10 rounded-lg border border-[var(--color-border)] px-3"><option value="single">اختيار فردي</option><option value="multiple">اختيار متعدد</option><option value="text">نص</option></select><label className="flex items-center gap-2"><input type="checkbox" checked={Boolean(field.is_required)} onChange={e=>setFields(fields.map((f,i)=>i===index?{...f,is_required:e.target.checked}:f))}/>إلزامي</label><label className="flex items-center gap-2"><input type="checkbox" checked={Boolean(field.is_active)} onChange={e=>setFields(fields.map((f,i)=>i===index?{...f,is_active:e.target.checked}:f))}/>نشط</label><button type="button" onClick={()=>setFields(fields.filter((_,i)=>i!==index))} className="text-sm text-[#C62828]">إزالة</button></div>{field.field_type!=='text'?<OptionsEditor options={field.options??[]} onChange={options=>setFields(fields.map((f,i)=>i===index?{...f,options}:f))}/>:null}</div>)}</div><div className="mt-6 flex justify-end border-t border-[var(--color-border)] pt-5"><Button disabled={saving} onClick={()=>onSave(fields.filter(f=>String(f.label_ar??'').trim()).map((f,i)=>({id:f.id||'',labelAr:f.label_ar,fieldType:f.field_type,isRequired:f.is_required,isActive:f.is_active,sortOrder:i+1,options:(f.options??[]).map((o:any,j:number)=>({id:o.id||'',labelAr:o.label_ar,isActive:o.is_active!==false,sortOrder:j+1}))})))}>حفظ التخصيص</Button></div></section>}
function OptionsEditor({options,onChange}:{options:any[];onChange:(options:any[])=>void}){return <div className="mt-4 flex flex-wrap gap-2">{options.map((option,index)=><div key={option.id||index} className="flex items-center gap-2 rounded-lg bg-[var(--color-bg)] p-2"><input value={option.label_ar??''} onChange={e=>onChange(options.map((o,i)=>i===index?{...o,label_ar:e.target.value}:o))} className="h-8 w-36 rounded border border-[var(--color-border)] bg-white px-2 text-xs"/><button type="button" onClick={()=>onChange(options.filter((_,i)=>i!==index))}>×</button></div>)}<button type="button" onClick={()=>onChange([...options,{id:'',label_ar:'',is_active:true,sort_order:options.length+1}])} className="rounded-lg border border-dashed border-[var(--color-border)] px-3 py-2 text-xs">+ خيار</button></div>}
