import { useCallback, useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { listDashboardProducts } from '@/data/dashboard'
import { useDashboard } from '@/state/DashboardContext'
import type { DashboardListResponse, DashboardProductListItem } from '@/types/dashboard'
import { DashboardEmpty, DashboardError, DashboardLoading } from '@/components/dashboard/DashboardStates'
import { DashboardTable, DashboardTd, DashboardTr } from '@/components/dashboard/DashboardTable'
import { formatJod } from '@/lib/format'
import { canCreateOrImportProducts } from '@/lib/dashboardPermissions'
import ProductCreateDrawer from '@/components/dashboard/ProductCreateDrawer'

export default function ProductsPage() {
  const { runtime, role } = useDashboard()
  const navigate = useNavigate()
  const [data,setData]=useState<DashboardListResponse<DashboardProductListItem>|null>(null)
  const [q,setQ]=useState(''); const [channel,setChannel]=useState(''); const [status,setStatus]=useState(''); const [availability,setAvailability]=useState(''); const [error,setError]=useState(false); const [createOpen,setCreateOpen]=useState(false)
  const load=useCallback(async()=>{try{setError(false);setData(await listDashboardProducts(runtime,{q,channel,status,availability,pageSize:50}))}catch{setError(true)}},[runtime,q,channel,status,availability])
  useEffect(()=>{const t=setTimeout(()=>void load(),180);return()=>clearTimeout(t)},[load])
  if(error)return <DashboardError onRetry={()=>void load()}/>
  if(!data)return <DashboardLoading/>
  const canCreate=runtime.mode === 'preview' || canCreateOrImportProducts(role)
  return <main className="space-y-5 p-4 lg:p-8" dir="rtl">
    <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><h2 className="text-2xl font-bold">إدارة المنتجات</h2><p className="mt-1 text-sm text-[var(--color-text-muted)]">إنشاء وتحديث B2C وB2B من مكان واحد، مع إدارة الوحدات والتخصيص بسهولة.</p></div>{canCreate?<div className="flex gap-2"><Link to="/dashboard/products/import" className="inline-flex h-10 items-center rounded-xl border border-[var(--color-border)] bg-[var(--color-surface)] px-4 text-sm font-semibold">استيراد Bulk</Link><button type="button" onClick={()=>setCreateOpen(true)} className="inline-flex h-10 items-center rounded-xl bg-[var(--color-text)] px-4 text-sm font-semibold text-[var(--color-on-primary)]">+ إضافة منتج</button></div>:null}</div>
    <section className="rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)] p-4"><div className="grid gap-3 md:grid-cols-[minmax(220px,1fr)_repeat(3,170px)]"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="بحث باسم المنتج أو SKU" className="h-11 rounded-xl border border-[var(--color-border)] bg-white px-3 outline-none"/><Filter value={channel} onChange={setChannel} options={[['','كل القنوات'],['B2C','B2C'],['B2B','B2B'],['BOTH','BOTH']]}/><Filter value={status} onChange={setStatus} options={[['','كل الحالات'],['DRAFT','مسودة'],['ACTIVE','نشط'],['INACTIVE','غير نشط'],['ARCHIVED','مؤرشف']]}/><Filter value={availability} onChange={setAvailability} options={[['','كل التوفر'],['AVAILABLE','متاح'],['UNAVAILABLE','غير متاح'],['SEASONAL','موسمي']]}/></div><p className="mt-3 text-xs text-[var(--color-text-muted)]">SKU هو الرمز الداخلي الفريد للمنتج؛ يساعد الفريق في البحث والتطابق والاستيراد.</p><div className="mt-4 flex items-center justify-between border-t border-[var(--color-border)] pt-3"><button type="button" onClick={()=>{setQ('');setChannel('');setStatus('');setAvailability('')}} className="text-xs underline underline-offset-4">مسح الفلاتر</button><p className="text-xs text-[var(--color-text-muted)]">{data.total} منتج</p></div></section>
    {data.items.length===0?<DashboardEmpty title="لا توجد منتجات" description="لا توجد منتجات مطابقة للفلاتر الحالية."/>:<><div className="space-y-3 md:hidden">{data.items.map(product=><Link key={product.id} to={`/dashboard/products/${product.id}/edit`} className="block rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)] p-4"><div className="flex items-start justify-between gap-3"><div className="flex flex-wrap gap-2"><Availability value={product.availability}/><span className={`rounded-full px-2 py-1 text-xs ${product.public_visible?'bg-[#E8F5E9] text-[#2E7D32]':'bg-[var(--color-bg)] text-[var(--color-text-muted)]'}`}>{product.public_visible?'عام':'مخفي'}</span></div><div className="min-w-0 text-right"><strong className="block truncate">{product.name_ar}</strong><span className="mt-1 block text-xs text-[var(--color-text-muted)]">{product.category_name||'بدون تصنيف'} · {product.sku||'بدون SKU'}</span></div></div><div className="mt-3 flex items-center justify-between border-t border-[var(--color-border)] pt-3 text-sm"><span dir="ltr" className="font-bold">{product.base_price_jod!=null?formatJod(Number(product.base_price_jod)):'--'}</span><span className="rounded-full bg-[var(--color-bg)] px-2 py-1 text-xs font-semibold">{product.channel}</span></div></Link>)}</div><div className="hidden md:block"><DashboardTable headers={['إجراءات','الظهور','التوفر','القناة','السعر الأساسي','التصنيف','المنتج']} minWidth={1050}>{data.items.map(product=><DashboardTr key={product.id} onClick={()=>navigate(`/dashboard/products/${product.id}/edit`)}><DashboardTd onClick={event=>event.stopPropagation()}><Link to={`/dashboard/products/${product.id}/edit`} className="rounded-lg bg-[var(--color-bg)] px-3 py-1.5 text-xs font-semibold">فتح</Link></DashboardTd><DashboardTd><span className={`rounded-full px-2 py-1 text-xs ${product.public_visible?'bg-[#E8F5E9] text-[#2E7D32]':'bg-[var(--color-bg)] text-[var(--color-text-muted)]'}`}>{product.public_visible?'عام':'مخفي'}</span></DashboardTd><DashboardTd><Availability value={product.availability}/></DashboardTd><DashboardTd><span className="rounded-full bg-[var(--color-bg)] px-2 py-1 text-xs font-semibold">{product.channel}</span></DashboardTd><DashboardTd>{product.base_price_jod!=null?formatJod(Number(product.base_price_jod)):'--'}</DashboardTd><DashboardTd>{product.category_name||'--'}</DashboardTd><DashboardTd><strong className="block">{product.name_ar}</strong><span className="text-[11px] text-[var(--color-text-muted)]">{product.sku||'بدون SKU'} · {product.status}</span></DashboardTd></DashboardTr>)}</DashboardTable></div></>}
  {createOpen?<ProductCreateDrawer runtime={runtime} onClose={()=>setCreateOpen(false)} onCreated={id=>{setCreateOpen(false);navigate(`/dashboard/products/${id}/edit`)}}/>:null}</main>
}
function Filter({value,onChange,options}:{value:string;onChange:(value:string)=>void;options:Array<[string,string]>}){return <select value={value} onChange={e=>onChange(e.target.value)} className="h-11 rounded-xl border border-[var(--color-border)] bg-white px-3 text-sm">{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>}
function Availability({value}:{value:string}){const map:any={AVAILABLE:['متاح','bg-[#E8F5E9] text-[#2E7D32]'],UNAVAILABLE:['غير متاح','bg-[#FDECEC] text-[#C62828]'],SEASONAL:['موسمي','bg-[#FFF3E0] text-[#E65100]']};const [label,cls]=map[value]??[value,'bg-[var(--color-bg)]'];return <span className={`rounded-full px-2 py-1 text-xs ${cls}`}>{label}</span>}
