import { useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import Button from '@/components/ui/Button'
import { getPublicCategories, type CatalogCategory } from '@/data/catalog'
import { createDashboardProduct } from '@/data/dashboard'
import { useDashboard } from '@/state/DashboardContext'
import { canCreateOrImportProducts } from '@/lib/dashboardPermissions'
import { DashboardRestricted } from '@/components/dashboard/DashboardStates'

export const emptyProductDraft={nameAr:'',sku:'',channel:'BOTH',categoryId:'',basePriceJod:'',availability:'AVAILABLE',status:'DRAFT',publicVisible:false,b2bAllowCustomUnit:false}
export type ProductDraft=typeof emptyProductDraft
export function ProductFields({draft,setDraft,categories}:{draft:ProductDraft;setDraft:(value:ProductDraft)=>void;categories:CatalogCategory[]}){return <><div className="grid gap-5 sm:grid-cols-2"><Field label="اسم المنتج" value={draft.nameAr} onChange={v=>setDraft({...draft,nameAr:v})}/><label><span className="mb-2 block text-sm font-semibold">SKU <span className="font-normal text-[var(--color-text-muted)]">(رمز المنتج الداخلي)</span></span><input value={draft.sku} onChange={e=>setDraft({...draft,sku:e.target.value})} className="h-11 w-full rounded-xl border border-[var(--color-border)] bg-white px-3 outline-none"/><span className="mt-1 block text-xs leading-5 text-[var(--color-text-muted)]">رمز فريد للإدارة والبحث والاستيراد، مثال: CM-CAKE-001.</span></label><label><span className="mb-2 block text-sm font-semibold">القناة</span><select value={draft.channel} onChange={e=>setDraft({...draft,channel:e.target.value})} className="h-11 w-full rounded-xl border border-[var(--color-border)] bg-white px-3"><option value="B2C">B2C</option><option value="B2B">B2B</option><option value="BOTH">BOTH</option></select></label><label><span className="mb-2 block text-sm font-semibold">التصنيف</span><select value={draft.categoryId} onChange={e=>setDraft({...draft,categoryId:e.target.value})} className="h-11 w-full rounded-xl border border-[var(--color-border)] bg-white px-3"><option value="">بدون تصنيف</option>{categories.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></label><Field label="السعر الأساسي JOD (اختياري)" type="number" value={draft.basePriceJod} onChange={v=>setDraft({...draft,basePriceJod:v})}/><label><span className="mb-2 block text-sm font-semibold">التوفر</span><select value={draft.availability} onChange={e=>setDraft({...draft,availability:e.target.value})} className="h-11 w-full rounded-xl border border-[var(--color-border)] bg-white px-3"><option value="AVAILABLE">متاح</option><option value="UNAVAILABLE">غير متاح</option><option value="SEASONAL">موسمي</option></select></label></div><div className="mt-5 grid gap-3 rounded-xl bg-[var(--color-bg)] p-4 sm:grid-cols-2"><label className="flex items-center gap-2"><input type="checkbox" checked={draft.publicVisible} onChange={e=>setDraft({...draft,publicVisible:e.target.checked})}/><span className="text-sm">ظاهر للعامة</span></label><label className="flex items-center gap-2"><input type="checkbox" checked={draft.b2bAllowCustomUnit} onChange={e=>setDraft({...draft,b2bAllowCustomUnit:e.target.checked})}/><span className="text-sm">السماح بوحدة مخصصة B2B</span></label></div></>}

export default function ProductCreatePage(){const {runtime,role}=useDashboard();const navigate=useNavigate();const [categories,setCategories]=useState<CatalogCategory[]>([]);const [draft,setDraft]=useState<ProductDraft>(emptyProductDraft);const [saving,setSaving]=useState(false);const [error,setError]=useState('');useEffect(()=>{void getPublicCategories().then(setCategories).catch(()=>setCategories([]))},[]);if(runtime.mode!=='preview'&&!canCreateOrImportProducts(role))return <DashboardRestricted/>;const save=async()=>{if(!draft.nameAr.trim()||!draft.sku.trim()){setError('اسم المنتج وSKU مطلوبان.');return}try{setSaving(true);setError('');const result=await createDashboardProduct(runtime,draft);navigate(`/dashboard/products/${result.product.id}/edit`)}catch(err:any){setError(String(err?.message??'تعذر إنشاء المنتج'))}finally{setSaving(false)}};return <main className="space-y-6 p-4 lg:p-8" dir="rtl"><div className="text-sm text-[var(--color-text-muted)]"><Link to="/dashboard/products">المنتجات</Link> ‹ <strong>إضافة منتج</strong></div><div><h2 className="text-2xl font-bold">إضافة منتج جديد</h2><p className="mt-1 text-sm text-[var(--color-text-muted)]">ابدأ بالمعلومات الضرورية فقط، ثم أكمل الوحدات والتخصيص من صفحة المنتج.</p></div>{error?<div className="rounded-xl bg-[#FDECEC] p-3 text-sm text-[#C62828]">{error}</div>:null}<section className="mx-auto max-w-3xl rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)] p-5 lg:p-8"><ProductFields draft={draft} setDraft={setDraft} categories={categories}/><div className="mt-7 flex justify-end gap-3 border-t border-[var(--color-border)] pt-5"><Link to="/dashboard/products" className="inline-flex h-10 items-center rounded-lg px-4 text-sm">إلغاء</Link><Button disabled={saving} onClick={()=>void save()}>{saving?'جاري الإنشاء...':'إنشاء ومتابعة التعديل'}</Button></div></section></main>}
function Field({label,value,onChange,type='text'}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <label><span className="mb-2 block text-sm font-semibold">{label}</span><input type={type} step={type==='number'?'0.001':undefined} value={value} onChange={e=>onChange(e.target.value)} className="h-11 w-full rounded-xl border border-[var(--color-border)] bg-white px-3 outline-none"/></label>}
