import { useCallback,useEffect,useState } from 'react'
import { Link,useNavigate } from 'react-router-dom'
import { getDashboardHome } from '@/data/dashboard'
import { useDashboard } from '@/state/DashboardContext'
import type { DashboardHomeData } from '@/types/dashboard'
import { DashboardError,DashboardLoading } from '@/components/dashboard/DashboardStates'
import { DashboardTable,DashboardTd,DashboardTr } from '@/components/dashboard/DashboardTable'
import { RequestStatusBadge } from '@/components/dashboard/DashboardStatusBadge'
const stats=[['إجمالي الطلبات','total'],['طلبات جديدة','new'],['بانتظار التأكيد','awaitingConfirmation'],['معتمدة','approved'],['قيد التجهيز','preparing'],['جاهزة للتسليم','ready']] as const
function relativeTime(value:string){const minutes=Math.max(1,Math.round((Date.now()-new Date(value).getTime())/60000));if(minutes<60)return 'منذ '+minutes+' دقيقة';const hours=Math.round(minutes/60);return hours<24?'منذ '+hours+' ساعة':'منذ '+Math.round(hours/24)+' يوم'}
export default function DashboardHomePage(){const {runtime}=useDashboard();const navigate=useNavigate();const [data,setData]=useState<DashboardHomeData|null>(null);const [error,setError]=useState(false);const load=useCallback(async()=>{try{setError(false);setData(await getDashboardHome(runtime))}catch{setError(true)}},[runtime]);useEffect(()=>{void load()},[load]);if(error)return <DashboardError onRetry={()=>void load()}/>;if(!data)return <DashboardLoading/>;return <main className="space-y-6 p-4 lg:p-8" dir="rtl"><section className="rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)] p-6 text-right"><h2 className="text-xl font-bold">أهلاً بك مجدداً</h2><p className="mt-1 text-sm text-[var(--color-text-muted)]">ملخص النشاط التشغيلي لهذا اليوم</p></section><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{stats.map(([label,key])=><div key={key} className="rounded-xl border border-[rgba(231,217,200,.5)] bg-[var(--color-surface)] p-5 text-right"><p className="text-[13px] text-[#78716C]">{label}</p><strong dir="ltr" className="mt-3 block text-right text-3xl">{data.stats[key]}</strong></div>)}</section><section className="rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)] p-4 lg:p-6"><div className="mb-4 flex items-center justify-between"><h2 className="font-semibold">آخر الطلبات الواردة</h2><Link to="/dashboard/requests" className="text-xs text-[var(--color-text-muted)]">عرض الكل</Link></div><div className="space-y-2 md:hidden">{data.recent.map(request=><button type="button" key={request.id} onClick={()=>navigate('/dashboard/requests/'+request.id)} className="w-full rounded-xl border border-[var(--color-border)] bg-white p-3 text-right"><div className="flex items-start justify-between gap-3"><RequestStatusBadge status={request.status}/><div><p dir="ltr" className="text-sm font-bold">{request.reference}</p><p className="mt-1 text-sm font-semibold">{request.customer_label}</p></div></div><div className="mt-2 flex justify-between border-t border-[var(--color-border)] pt-2 text-xs text-[var(--color-text-muted)]"><span>{request.customer_type}</span><span>{relativeTime(request.submitted_at)}</span></div></button>)}</div><div className="hidden md:block"><DashboardTable headers={['المرجع','العميل / الشركة','النوع','الحالة','تاريخ الإنشاء']} minWidth={700}>{data.recent.map(request=><DashboardTr key={request.id} onClick={()=>navigate('/dashboard/requests/'+request.id)}><DashboardTd className="font-bold text-[var(--color-text-muted)]">{request.reference}</DashboardTd><DashboardTd className="font-semibold">{request.customer_label}</DashboardTd><DashboardTd className={request.customer_type==='B2B'?'text-[var(--color-accent)]':''}>{request.customer_type}</DashboardTd><DashboardTd><RequestStatusBadge status={request.status}/></DashboardTd><DashboardTd className="text-xs text-[#78716C]">{relativeTime(request.submitted_at)}</DashboardTd></DashboardTr>)}</DashboardTable></div></section></main>}
