import { Navigate, Outlet } from 'react-router-dom'
import { useEffect, useState } from 'react'
import { DashboardProvider, useDashboard } from '@/state/DashboardContext'
import { DashboardPreferencesProvider, useDashboardPreferences } from '@/state/DashboardPreferencesContext'
import { DashboardSidebar, DashboardTopbar } from '@/components/dashboard/DashboardChrome'
import { DashboardLoading } from '@/components/dashboard/DashboardStates'
import { getPlatformSettings } from '@/data/platform'
function DashboardFrame(){const {runtime,loading,role}=useDashboard();const {locale}=useDashboardPreferences();const[enabled,setEnabled]=useState<boolean|null>(null);useEffect(()=>{if(runtime.mode==='secure')void getPlatformSettings(runtime).then(x=>setEnabled(x.appEnabled)).catch(()=>setEnabled(true))},[runtime]);if(loading||enabled===null&&runtime.mode==='secure')return <DashboardLoading/>;if(runtime.mode==='unauthorized')return <Navigate to="/dashboard/login" replace/>;if(runtime.mode==='secure'&&runtime.access?.mustChangePassword)return <Navigate to="/dashboard/change-password" replace/>;if(enabled===false&&role!=='SUPER_ADMIN')return <main dir={locale==='en'?'ltr':'rtl'} className="grid min-h-screen place-items-center bg-[var(--color-bg)] p-5 text-center"><section className="max-w-md rounded-3xl border border-[var(--color-border)] bg-[var(--color-surface)] p-8"><h1 className="text-2xl font-bold">{locale==='en'?'Application temporarily unavailable':'التطبيق غير متاح مؤقتًا'}</h1><p className="mt-3 text-[var(--color-text-muted)]">{locale==='en'?'Access has been paused by the system manager.':'تم إيقاف الوصول مؤقتًا من مدير النظام.'}</p></section></main>;return <div dir={locale==='en'?'ltr':'rtl'} className="min-h-screen bg-[var(--color-bg)] text-[var(--color-text)]"><DashboardSidebar/><div className={'min-h-screen '+(locale==='en'?'lg:ml-[260px]':'lg:mr-[260px]')}><DashboardTopbar/><Outlet/></div></div>}
export default function DashboardLayout(){return <DashboardPreferencesProvider><DashboardProvider><DashboardFrame/></DashboardProvider></DashboardPreferencesProvider>}
