import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import Button from '@/components/ui/Button'
import { getPublicCategories, type CatalogCategory } from '@/data/catalog'
import { importDashboardProducts, previewDashboardProductImport } from '@/data/dashboard'
import { downloadBulkProductTemplate, parseBulkProductFile, type BulkProductRow } from '@/lib/bulkProducts'
import { useDashboard } from '@/state/DashboardContext'
import { canCreateOrImportProducts } from '@/lib/dashboardPermissions'
import { DashboardRestricted } from '@/components/dashboard/DashboardStates'
import type { DashboardProductImportPreview, DashboardProductImportResult } from '@/types/dashboard'

export default function ProductBulkImportPage(){
  const {runtime,role}=useDashboard(); const [categories,setCategories]=useState<CatalogCategory[]>([]); const [rows,setRows]=useState<BulkProductRow[]>([]); const [preview,setPreview]=useState<DashboardProductImportPreview|null>(null); const [result,setResult]=useState<DashboardProductImportResult|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState('')
  useEffect(()=>{void getPublicCategories().then(setCategories).catch(()=>setCategories([]))},[])
  if(runtime.mode !== 'preview' && !canCreateOrImportProducts(role))return <DashboardRestricted/>
  const fileChange=async(file?:File)=>{if(!file)return;try{setBusy(true);setError('');setResult(null);const parsed=await parseBulkProductFile(file);setRows(parsed);setPreview(await previewDashboardProductImport(runtime,parsed))}catch(err:any){setError(String(err?.message??'تعذر قراءة الملف'));setRows([]);setPreview(null)}finally{setBusy(false)}}
  const runImport=async()=>{if(!preview||preview.invalid>0)return;try{setBusy(true);setError('');setResult(await importDashboardProducts(runtime,rows))}catch(err:any){setError(String(err?.message??'تعذر الاستيراد'))}finally{setBusy(false)}}
  return <main className="space-y-6 p-4 lg:p-8"><div className="text-sm text-[var(--color-text-muted)]"><Link to="/dashboard/products">المنتجات</Link> ‹ <strong>استيراد Bulk</strong></div><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><h2 className="text-2xl font-bold">استيراد منتجات Bulk</h2><p className="mt-1 max-w-2xl text-sm leading-6 text-[var(--color-text-muted)]">راجع المعاينة ثم استورد دفعة واحدة. المنتجات المتاحة ستظهر تلقائياً على موقع قناتها، وغير المتاحة ستبقى مخفية؛ لا توجد خطوة نشر أو مسودة.</p></div><Button variant="secondary" onClick={()=>downloadBulkProductTemplate(categories)}>تنزيل Template XLSX</Button></div>
    <section className="rounded-2xl border border-dashed border-[var(--color-border)] bg-[var(--color-surface)] p-8 text-center"><input id="bulk-file" type="file" accept=".xlsx,.xls,.csv" className="hidden" onChange={e=>void fileChange(e.target.files?.[0])}/><label htmlFor="bulk-file" className="mx-auto inline-flex cursor-pointer rounded-xl bg-[var(--color-text)] px-6 py-3 text-sm font-semibold text-[var(--color-on-primary)]">اختيار ملف CSV / XLSX</label><p className="mt-3 text-xs text-[var(--color-text-muted)]">SKU جديد = إنشاء، وSKU موجود = تحديث. التوفر يضبط النشر تلقائياً.</p></section>
    {error?<div className="rounded-xl bg-[#FDECEC] p-4 text-sm text-[#C62828]">{error}</div>:null}
    {busy&&!preview?<div className="rounded-xl bg-[var(--color-surface)] p-5 text-sm">جاري فحص الملف...</div>:null}
    {preview?<><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[['إجمالي',preview.total],['صالح',preview.valid],['أخطاء',preview.invalid],['إنشاء',preview.creates],['تحديث',preview.updates]].map(([label,value])=><div key={String(label)} className="rounded-xl border border-[var(--color-border)] bg-[var(--color-surface)] p-4 text-right"><p className="text-xs text-[var(--color-text-muted)]">{label}</p><strong className="mt-1 block text-2xl">{value}</strong></div>)}</div><section className="overflow-hidden rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)]"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-right text-sm"><thead className="bg-[var(--color-bg)]"><tr><th className="p-3">الصف</th><th className="p-3">SKU</th><th className="p-3">المنتج</th><th className="p-3">القناة</th><th className="p-3">التوفر</th><th className="p-3">الإجراء والنتيجة</th></tr></thead><tbody>{preview.rows.map(row=><tr key={row.row} className="border-t border-[var(--color-border)]"><td className="p-3">{row.row}</td><td className="p-3 font-mono text-xs">{row.sku}</td><td className="p-3 font-semibold">{row.nameAr}</td><td className="p-3">{row.channel}</td><td className="p-3">{row.availability==='AVAILABLE'?'متاح':'غير متاح'}</td><td className="p-3">{row.valid?<span className="text-[#2E7D32]">{row.action==='CREATE'?'إنشاء':'تحديث'} · {row.availability==='AVAILABLE'?'سيظهر تلقائياً':'سيبقى مخفياً'}</span>:<div className="text-xs text-[#C62828]">{row.errors.join(' · ')}</div>}</td></tr>)}</tbody></table></div></section><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-xs text-[var(--color-text-muted)]">أي منتج قناة واحدة فقط: B2C أو B2B. لإضافته للقناتين استخدم SKU مختلفاً لكل قناة. لن يتم الاستيراد إذا وُجد صف غير صالح.</p><Button disabled={busy||preview.invalid>0||preview.total===0} onClick={()=>void runImport()}>{busy?'جاري الاستيراد...':'استيراد المنتجات وتطبيق الظهور تلقائياً'}</Button></div></>:null}
    {result?<div className="rounded-2xl border border-[#C8E6C9] bg-[#F1F8F2] p-6 text-right"><h3 className="text-lg font-bold text-[#2E7D32]">تم الاستيراد بنجاح</h3><p className="mt-2 text-sm">تم إنشاء {result.created} وتحديث {result.updated} منتج.</p><Link to="/dashboard/products" className="mt-4 inline-flex text-sm font-semibold underline underline-offset-4">العودة إلى المنتجات</Link></div>:null}
  </main>
}
