import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import ImageUploadField from '@/components/dashboard/ImageUploadField'
import { getDashboardBrandSettings, updateDashboardBrandSettings } from '@/data/dashboard'
import { getPlatformSettings, listDataSnapshots, resetData, restoreDataSnapshot, updatePlatformSettings, type DataSnapshot } from '@/data/platform'
import { useDashboard } from '@/state/DashboardContext'
import { useDashboardPreferences } from '@/state/DashboardPreferencesContext'
import { dashboardText } from '@/lib/dashboardI18n'
import { canManageUsers } from '@/lib/dashboardPermissions'

const en = { platform:'Platform status', website:'Public website', app:'Operations app', on:'On', off:'Off', save:'Save platform status', reset:'Data reset', backup:'Backups', restore:'Restore backup', scope:'Reset scope', confirm:'Type RESET to confirm', operational:'Requests and customers', catalog:'Products and categories', content:'Website content', full:'Full reset' }
const ar = { platform:'حالة المنصات', website:'الموقع العام', app:'التطبيق التشغيلي', on:'مُشغّل', off:'متوقف', save:'حفظ حالة المنصات', reset:'إعادة ضبط البيانات', backup:'النسخ الاحتياطية', restore:'استعادة النسخة', scope:'نطاق إعادة الضبط', confirm:'اكتب RESET للتأكيد', operational:'الطلبات والعملاء', catalog:'المنتجات والتصنيفات', content:'محتوى الموقع', full:'إعادة ضبط كاملة' }
type ResetNotice = { type: 'success' | 'error'; text: string } | null

export default function SettingsPage() {
  const { role, runtime } = useDashboard(); const { locale, setLocale } = useDashboardPreferences(); const t = locale === 'en' ? en : ar; const superAdmin = role === 'SUPER_ADMIN'
  const [logo, setLogo] = useState(''); const [website, setWebsite] = useState(true); const [app, setApp] = useState(true); const [scope, setScope] = useState<DataSnapshot['scope']>('OPERATIONAL'); const [confirm, setConfirm] = useState(''); const [snapshots, setSnapshots] = useState<DataSnapshot[]>([]); const [busy, setBusy] = useState<'platform'|'logo'|'reset'|'restore'|null>(null); const [resetNotice, setResetNotice] = useState<ResetNotice>(null)
  const load = async () => { const [brand, platform, backups] = await Promise.all([getDashboardBrandSettings(runtime), getPlatformSettings(runtime), superAdmin ? listDataSnapshots(runtime) : Promise.resolve([])]); setLogo(brand.logoUrl ?? ''); setWebsite(platform.websiteEnabled); setApp(platform.appEnabled); setSnapshots(backups) }
  useEffect(() => { void load() }, [runtime, superAdmin])
  const savePlatform = async () => { setBusy('platform'); try { await updatePlatformSettings(runtime, website, app) } finally { setBusy(null) } }
  const reset = async () => { if (confirm !== 'RESET') return; setBusy('reset'); setResetNotice(null); try { await resetData(runtime, scope); setConfirm(''); await load(); setResetNotice({ type:'success', text:locale === 'en' ? 'Reset completed. A backup is ready to restore.' : 'تمت إعادة الضبط بنجاح. تم إنشاء نسخة احتياطية ويمكنك استعادتها من القائمة أدناه.' }) } catch (error) { setResetNotice({ type:'error', text:error instanceof Error ? error.message : (locale === 'en' ? 'Could not reset data. No changes were completed.' : 'تعذرت إعادة ضبط البيانات. لم تكتمل أي تغييرات.') }) } finally { setBusy(null) } }
  const restore = async (id:string) => { if (!window.confirm(locale === 'en' ? 'Replace current data with this backup?' : 'سيتم استبدال البيانات الحالية بهذه النسخة. هل تريد المتابعة؟')) return; setBusy('restore'); setResetNotice(null); try { await restoreDataSnapshot(runtime,id); await load(); setResetNotice({type:'success',text:locale === 'en' ? 'Backup restored successfully.' : 'تمت استعادة النسخة الاحتياطية بنجاح.'}) } catch (error) { setResetNotice({type:'error',text:error instanceof Error ? error.message : (locale === 'en' ? 'Could not restore this backup.' : 'تعذرت استعادة هذه النسخة.')}) } finally { setBusy(null) } }
  return <main className="space-y-6 p-4 lg:p-8" dir={locale === 'en' ? 'ltr' : 'rtl'}>
    <section className="rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)] p-6"><h1 className="text-xl font-bold">{dashboardText(locale,'title.settings')}</h1><p className="mt-2 text-sm text-[var(--color-text-muted)]">{locale === 'en' ? 'Internal operations settings.' : 'إعدادات التشغيل والوصول الداخلي.'}</p></section>
    <Card title={dashboardText(locale,'settings.language')}><div className="flex gap-3"><button onClick={()=>setLocale('ar')} className={locale === 'ar' ? active : idle}>العربية</button><button onClick={()=>setLocale('en')} className={locale === 'en' ? active : idle}>English</button></div></Card>
    <Card title={t.platform}><div className="space-y-3"><Switch checked={website} onChange={setWebsite} label={t.website} detail={locale === 'en' ? 'Show a maintenance page to visitors while disabled.' : 'يعرض صفحة صيانة للزوار عند الإيقاف.'} t={t}/><Switch checked={app} onChange={setApp} label={t.app} detail={locale === 'en' ? 'Pause kitchen and operational access; the system manager remains able to restore access.' : 'يوقف وصول المطبخ والتطبيق؛ مدير النظام يبقى قادرًا على استعادة الوصول.'} t={t}/></div>{superAdmin?<button disabled={busy !== null} onClick={()=>void savePlatform()} className="mt-5 rounded-xl bg-[#2E1E17] px-5 py-3 text-sm font-bold text-white disabled:opacity-50">{busy === 'platform' ? (locale === 'en' ? 'Saving...' : 'جاري الحفظ...') : t.save}</button>:null}</Card>
    <Card title={locale === 'en' ? 'Dashboard logo' : 'لوجو لوحة التحكم'}><ImageUploadField label={locale === 'en' ? 'Dashboard logo' : 'لوجو الداشبورد'} value={logo} onChange={setLogo} storagePath="dashboard/brand-logo" help="PNG أو WebP" recommendedSize="512 × 512 px · 1:1" disabled={runtime.mode === 'preview'} sharedNote=""/><button disabled={busy !== null} onClick={async()=>{setBusy('logo');try{await updateDashboardBrandSettings(runtime,logo)}finally{setBusy(null)}}} className="mt-4 rounded-xl bg-[#2E1E17] px-5 py-3 text-sm font-bold text-white disabled:opacity-50">{busy === 'logo' ? (locale === 'en' ? 'Saving...' : 'جاري الحفظ...') : (locale === 'en' ? 'Save logo' : 'حفظ اللوجو')}</button></Card>
    {superAdmin?<Card title={t.reset}><p className="text-sm text-[var(--color-text-muted)]">{locale === 'en' ? 'A restorable backup is created before every reset.' : 'يتم إنشاء نسخة احتياطية قابلة للاستعادة قبل كل إعادة ضبط.'}</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><label><span className="mb-2 block text-sm font-semibold">{t.scope}</span><select value={scope} disabled={busy !== null} onChange={e=>setScope(e.target.value as DataSnapshot['scope'])} className="h-11 w-full rounded-xl border border-[var(--color-border)] bg-white px-3"><option value="OPERATIONAL">{t.operational}</option><option value="CATALOG">{t.catalog}</option><option value="CONTENT">{t.content}</option><option value="FULL">{t.full}</option></select></label><label><span className="mb-2 block text-sm font-semibold">{t.confirm}</span><input value={confirm} placeholder="RESET" disabled={busy !== null} onChange={e=>setConfirm(e.target.value)} className="h-11 w-full rounded-xl border border-[var(--color-border)] px-3"/></label></div>{confirm !== 'RESET'?<p className="mt-3 text-xs text-[var(--color-text-muted)]">{locale === 'en' ? 'Enter RESET exactly to enable the action.' : 'اكتب RESET بالإنجليزية كما هي لتفعيل الزر.'}</p>:null}<button disabled={busy !== null || confirm !== 'RESET'} onClick={()=>void reset()} className="mt-4 inline-flex min-w-44 items-center justify-center rounded-xl bg-[#B3261E] px-5 py-3 text-sm font-bold text-white disabled:opacity-40">{busy === 'reset' ? (locale === 'en' ? 'Creating backup and resetting…' : 'جاري إنشاء النسخة وإعادة الضبط...') : t.reset}</button>{busy === 'reset'?<div role="status" className="mt-4 rounded-xl bg-[#FFF4E5] p-4 text-sm font-semibold text-[#8A4B08]">{locale === 'en' ? 'Do not close this page. Your backup is being created, then the selected data is reset.' : 'لا تغلق الصفحة. يتم الآن إنشاء النسخة الاحتياطية ثم إعادة ضبط البيانات المحددة.'}</div>:null}{resetNotice?<div role="status" aria-live="polite" className={'mt-4 rounded-xl p-4 text-sm font-semibold '+(resetNotice.type === 'success' ? 'bg-[#E8F5E9] text-[#2E7D32]' : 'bg-[#FFF1F1] text-[#9B2C2C]')}>{resetNotice.text}</div>:null}<h3 className="mt-7 border-t border-[var(--color-border)] pt-5 font-semibold">{t.backup}</h3><div className="mt-3 space-y-2">{snapshots.length ? snapshots.map(x=><div key={x.id} className="flex items-center justify-between gap-3 rounded-xl bg-[var(--color-bg)] p-3 text-sm"><button disabled={busy !== null} onClick={()=>void restore(x.id)} className="rounded-lg border border-[var(--color-border)] bg-white px-3 py-2 font-semibold disabled:opacity-50">{busy === 'restore' ? (locale === 'en' ? 'Restoring…' : 'جاري الاستعادة...') : t.restore}</button><span>{x.scope} · {new Date(x.createdAt).toLocaleString(locale === 'en' ? 'en-GB' : 'ar-JO')}</span></div>) : <p className="text-sm text-[var(--color-text-muted)]">{locale === 'en' ? 'No backups yet.' : 'لا توجد نسخ احتياطية بعد.'}</p>}</div></Card>:null}
    {canManageUsers(role)?<Link to="/dashboard/users" className="block max-w-2xl rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)] p-6 font-semibold hover:bg-[var(--color-bg)]">{dashboardText(locale,'settings.users')}</Link>:null}
  </main>
}
const active='rounded-xl bg-[var(--color-text)] px-4 py-3 text-sm font-semibold text-white',idle='rounded-xl border border-[var(--color-border)] px-4 py-3 text-sm'
function Card({title,children}:{title:string;children:any}){return <section className="max-w-2xl rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)] p-6"><h2 className="font-bold">{title}</h2><div className="mt-4">{children}</div></section>}
function Switch({checked,onChange,label,detail,t}:{checked:boolean;onChange:(x:boolean)=>void;label:string;detail:string;t:typeof ar|typeof en}){return <div className="flex items-center justify-between gap-4 rounded-xl bg-[var(--color-bg)] p-4"><button type="button" role="switch" aria-checked={checked} onClick={()=>onChange(!checked)} className={'relative h-7 w-12 rounded-full '+(checked?'bg-[#2E7D32]':'bg-[#A8A29E]')}><span className={'absolute top-1 size-5 rounded-full bg-white '+(checked?'right-1':'left-1')}/></button><div className="flex-1"><p className="font-semibold">{label} <span className="text-xs font-normal text-[var(--color-text-muted)]">— {checked?t.on:t.off}</span></p><p className="mt-1 text-xs leading-5 text-[var(--color-text-muted)]">{detail}</p></div></div>}
